version: '3.7'

services:
    api:
        image: portfolio-api:latest
        ports:
            - 9090:9090
        volumes:
            - ./resources:/go/src/resources
            # - ./dist:/go/src/dist
        env_file:
            - .env
    api-dev:
        image: portfolio-api-dev:latest
        ports:
            - 9090:9090
        volumes:
            - ./resources:/go/src/resources
            - ./dist:/go/src/dist
            - ./src:/go/src/src
        env_file:
            - .env
